apiVersion: v1
kind: DeploymentConfig
metadata:
  name: catalog
  namespace: {{PROJECT}}
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: nexus.dcocp.ibank.com/catalog:{{TAG_IMAGE}}
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: nexus