apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-18T11:11:06Z"
  labels:
    run: catalog
    hpecp.hpe.com/hpecp-internal-gateway: "true"
  name: catalog-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    name: "web"
    protocol: TCP
    targetPort: 8080
  selector:
    app: catalog
  sessionAffinity: None
  type: NodePort